stages:
  - build
  - test

variables:
  GIT_STRATEGY: clone

build:linux:
  cache:
    paths:
      - dist-newstyle/
  stage: build
  tags:
    - haskell
  artifacts:
    paths:
      - build/test/powerdns-gerd-test
      - build/test/powerdns-gerd.test.conf
      - build/powerdns-gerd
  script:
    - mkdir -p build/test
    - cabal build -j4 --enable-tests powerdns-gerd
    - cabal build -j4 --enable-tests powerdns-gerd:test:powerdns-gerd-test
    - cp $(cabal -v0 list-bin --enable-tests powerdns-gerd:test:powerdns-gerd-test) build/test/powerdns-gerd-test
    - cp $(cabal -v0 list-bin --enable-tests powerdns-gerd) build/powerdns-gerd
    - cp test/powerdns-gerd.test.conf build/test/powerdns-gerd.test.conf

build:linux:static:
  cache:
    paths:
      - dist-newstyle/
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - build/powerdns-gerd
  image: alpine:latest
  variables:
    BOOTSTRAP_HASKELL_NONINTERACTIVE: "1"
  before_script:
    - apk add libsodium-dev libsodium-static binutils-gold zlib-static zlib-dev curl
    - curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
  script:
    - mkdir build
    - cabal build --ghc-options='-optl-static -optl-pthread' --constraint='cryptonite +integer-simple -integer-gmp'
    - cp $(cabal list-bin --enable-tests powerdns-gerd) build/powerdns-gerd

test:
  image: ubuntu:focal
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    IN_GITLAB_CI: "yes"
  dependencies:
    - build:linux
  services:
    - name: registry.gitlab.com/wobcom/haskell/powerdns-gerd:pdns-service
      alias: pdns
  cache:
    paths:
      - dist-newstyle/
  stage: test
  tags:
    - docker
  script:
    - apt update
    - apt install --yes --no-install-recommends zlib1g libsodium23
    - cd build/
    - ./test/powerdns-gerd-test
