stages:
  - build
  - test

variables:
  GIT_STRATEGY: clone

build:linux:
  cache:
    paths:
      - dist-newstyle/
  stage: build
  tags:
    - haskell
  artifacts:
    paths:
      - build/powerdns-guard-test
  script:
    - mkdir build/
    - cabal build -j4 --enable-tests powerdns-guard
    - cabal build -j4 --enable-tests powerdns-guard:test:powerdns-guard-test
    - cp $(cabal -v0 list-bin --enable-tests powerdns-guard:test:powerdns-guard-test) build/powerdns-guard-test

test:
  image: ubuntu:focal
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  dependencies:
    - build:linux
  services:
    - name: registry.gitlab.com/wobcom/haskell/powerdns-guard:pdns-service
      alias: pdns
  cache:
    paths:
      - dist-newstyle/
  stage: test
  tags:
    - docker
  script:
    - apt update
    - apt install --yes --no-install-recommends zlib1g libsodium23
    - cd build/
    - ./powerdns-guard-test
