stages:
  - build
  - test

variables:
  GIT_STRATEGY: clone

build:linux:
  cache:
    paths:
      - dist-newstyle/
  stage: build
  tags:
    - haskell
  artifacts:
    paths:
      - build/test/powerdns-gerd-test
      - build/test/powerdns-gerd.test.conf
      - build/powerdns-gerd
  script:
    - mkdir -p build/test
    - cp .ci/ci.cabal.project cabal.project.local
    - cabal build powerdns-gerd
    - cabal build powerdns-gerd:test:powerdns-gerd-test
    - cp $(cabal -v0 list-bin powerdns-gerd:test:powerdns-gerd-test) build/test/powerdns-gerd-test
    - cp $(cabal -v0 list-bin powerdns-gerd) build/powerdns-gerd
    - cp test/powerdns-gerd.test.conf build/test/powerdns-gerd.test.conf

build:linux:static:
  cache:
    paths:
      - dist-newstyle/
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - build/powerdns-gerd
  image: alpine:latest
  variables:
    BOOTSTRAP_HASKELL_NONINTERACTIVE: "1"
  before_script:
    - apk add libsodium-dev libsodium-static binutils-gold zlib-static zlib-dev curl gcc gmp-dev libc-dev libffi-dev make musl-dev ncurses-dev perl tar xz
    - curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
    - source /root/.ghcup/env
  script:
    - mkdir build
    - cp .ci/static.cabal.project cabal.project.local
    - cabal build powerdns-gerd:exe:powerdns-gerd
    - cp $(cabal -v0 list-bin powerdns-gerd) build/powerdns-gerd

testExampleConfig:
  stage: test
  dependencies:
    - build:linux
  script:
    - ./build/powerdns-gerd config-test -c ./powerdns-gerd.conf.example

test:
  image: ubuntu:focal
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    IN_GITLAB_CI: "yes"
  dependencies:
    - build:linux
  services:
    - name: registry.gitlab.com/wobcom/haskell/powerdns-gerd:pdns-service
      alias: pdns
  cache:
    paths:
      - dist-newstyle/
  stage: test
  tags:
    - docker
  script:
    - apt update
    - apt install --yes --no-install-recommends zlib1g libsodium23
    - cd build/
    - ./test/powerdns-gerd-test
